name: Comment on binary size
on:
  workflow_run:
    workflows: [Binary size report]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/github-script@v5
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "bloat_comment.md"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: "zip",
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/bloat_comment.zip`, Buffer.from(download.data));

      - name: Unzip artifact and move to expected location
        run: |
          unzip bloat_comment.zip
          mkdir --parents ".github/workflows/"
          mv "bloat_comment.md" ".github/workflows/bloat_comment.md"

      - name: Comment artifact
        uses: NejcZdovc/comment-pr@v1
        with:
          file: "bloat_comment.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
