---
name: OpenSK code coverage report
on:
  push:
    paths:
      - 'src/**/*.rs'
      - 'libraries/**/*.rs'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  coveralls:
    name: OpenSK code coverage
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Install Rust toolchain
        run: rustup show
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Set up OpenSK
        run: ./setup.sh

      - name: Install cargo kcov
        run: cargo +stable install cargo-kcov
      - name: Install packages
        run: sudo apt-get install cmake g++ pkg-config jq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
      - name: Install kcov
        run: cargo kcov --print-install-kcov-sh | sh

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features with_ctap1,with_nfc,std
      - name: Install nightly to workaround ICE
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2021-09-25
            override: true
      - name: Run kcov
        run: cargo +nightly-2021-09-25 kcov --features with_ctap1,with_nfc,std --no-fail-fast --coveralls -- --exclude-pattern=third_party,/usr/lib/gcc,/home/kaczmarczyck/.cargo --coveralls-id=${{ secrets.GITHUB_TOKEN }}
        env:
          TRAVIS_JOB_ID: ${{ secrets.GITHUB_TOKEN }}

